typography_spectrum: 0.9686352864373475
color:
  brandStrength: 0.36766177555546165
  lightness: 0.18570358073338866
  saturation: 0.2624779869802296
  rhythmicContrast: 0.3208434977568686
  brandColors:
    - '#000000'
    - '#404040'
    - '#808080'
    - '#BFBFBF'
    - '#FFFFFF'
layout_spectrum: 0.02217496349476278
name: tibbar tales
navigation:
  - name: About
    url: 'http://artofmob.blogspot.com/p/about-contact.html'
    type: external
title: mobile photography
description: ...all from an iphone
