typography_spectrum: 0.23537306836806238
color:
  brandStrength: 0.8241220242343843
  lightness: 0.8029939096886665
  saturation: 0.2044695469085127
  rhythmicContrast: 0.7748835945967585
  brandColors:
    - '#D4D5D7'
    - '#6A617E'
    - '#A09697'
    - '#E5B6AC'
    - '#AD6070'
layout_spectrum: 0.4145754270721227
name: tibbar tales
navigation:
  - name: About
    url: 'http://artofmob.blogspot.com/p/about-contact.html'
    type: external
title: mobile photography
description: ...all from an iphone
